env:
   - TERM=dumb GROOVY_TURN_OFF_JAVA_WARNINGS=true
language: java
dist: trusty
matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.2
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: ./gradlew clean
script: ./gradlew -b build.gradle dist
branches:
  only:
    - master
deploy:
  provider: releases
  api_key: "$GitOAUTHToken"
  file_glob: true
  file: "./smaliex-bin/*.jar"
  skip_cleanup: true
  on:
    tags: false
    repo: ZeoRexDevs/SmaliEx
    branch: master
